### PR TITLE
Fixed VKUser object not getting created due to JSON body including a "data" parent dictionary

### PR DESCRIPTION
**Pull request by nuudles**
The JSON response looks like this:

    {"success":true,"data":{"userName":"nuudles","registrationDate":"2015-07-04T14:44:07.257Z","bio":"Aww snap, this user did not yet write their bio. If they did, it would show up here, you know.","profilePicture":"https://fakevout.azurewebsites.net/Graphics/thumb-placeholder.png","commentPoints":{"sum":0,"upCount":0,"downCount":0},"submissionPoints":{"sum":0,"upCount":0,"downCount":0},"commentVoting":{"sum":0,"upCount":0,"downCount":0},"submissionVoting":{"sum":0,"upCount":0,"downCount":0},"badges":[]}}

With a "success" and "data" field.

### CODE REVIEW

**Comment by nuudles** [comment]
Also fixed some authentication methods

**Comment by AmarJayR** [comment]
Thanks for the PR, just merged it.

**Comment by AmarJayR** [comment]
I have undone commit 7f8c927, only the data key gets passed to the + (id)objectFromJSON:(NSDictionary *)JSON. The real problem was in VKClient+Requests.m and has now been fixed.

**Comment by nuudles** [comment]
Looks good @AmarJayR , but I think you missed one spot in the VKObjectBuilder. On line 33 after your change it should be:

`id model = [MTLJSONAdapter modelOfClass:[VKUser class] fromJSONDictionary:JSON error:&error];`

Instead of:

`id model = [MTLJSONAdapter modelOfClass:[VKUser class] fromJSONDictionary:JSON[@"data"] error:&error];`

**Comment by AmarJayR** [comment]
Yup, you're right. Nice catch, fixed it in commit 4a213f969edca64a05b897b91de6ff7aaaa59a2c

**Pull request merged**
